# Generated by Django 5.2.8 on 2025-11-12 22:10

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('installed_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flood_m', models.FloatField()),
                ('reported_on', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensor.sensor')),
            ],
            options={
                'get_latest_by': 'reported_on',
                'indexes': [models.Index(fields=['reported_on'], name='sensor_read_reporte_744bfe_idx'), models.Index(fields=['sensor', 'reported_on'], name='sensor_read_sensor__76b2db_idx')],
            },
        ),
    ]
