# Generated by Django 5.2.8 on 2025-11-13 09:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_alter_sensor_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
