# Generated by Django 5.2.8 on 2025-11-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_alter_sensor_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='id',
            field=models.CharField(editable=False, primary_key=True, serialize=False),
        ),
    ]
