# Generated by Django 5.2.8 on 2025-11-15 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0005_alter_sensor_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading',
            options={'get_latest_by': 'reported_on', 'ordering': ['-reported_on']},
        ),
    ]
