# Generated by Django 5.2.8 on 2025-11-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0006_alter_reading_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
